function[psip,psi,psif] = eddyFrameStreamFunction(xp,yp,ssh,uo,vo,fo)
%eddyFrameStreamFunction  Streamfunction of an eddy in the co-moving frame.
%
%   PSIP = eddyFrameStreamFunction(XP,YP,SSH,UO,VO,FO) finds the 
%   streamfunction in the co-moving or eddy-fixed frame.  The "P" in XP,
%   YP, and PSIP could be read as "prime".
%
%   XP and YP are uniformly spaced 1D coordinate arrays in the co-moving 
%   frame, with the origin (0,0) corresponding to the eddy center. SSH is 
%   a 3D array of sea surface height with LENGTH(YP) rows and LENGTH(XP)
%   columns.  These are generated by CREATEEDDYFRAME.
%
%   UO and VO are the eastward and northward velocity components of the 
%   eddy center relative to the Earth. FO is the Coriolis frequency.
% 
%   In this function, units are important.  The units of XP and YP are km,
%   the units of SSH are m, UO and VO are in m/s, and FO has units of 1/s.
%   The streamfunction PSIP then has the mixed units m km / s.  
%
%   The geostrophic velocities UP, VP relative to the co-moving frame are 
%   then given by UP = -VDIFF(PSIP,1) / DX and VP = VDIFF(PSIP,2) / DX 
%   where DX = XP(2)-XP(1) is the sampling interval of the XP, YP 
%   coordinates.  VDIFF implements the first central difference.  
% 
%   [PSIP,PSI,PSIF] = eddyFrameStreamFunction(...) also returns PSI, the 
%   streamfunction for the flow relative to the Earth, and PSIF, the 
%   streamfunction for the eddy center velocity relative to the Earth. 
%
%   Note that all three streamfunctions have LENGTH(YP) rows and LENGTH(XP)
%   columns, that is, they are expressed with respect to the eddy-centered
%   or primed coordinates (XP,YP). 
%  
%   Usage: psip = eddyFrameStreamFunction(xp,yp,ssh,uo,vo,fo);
%          [psip,psi,psif] = eddyFrameStreamFunction(xp,yp,ssh,uo,vo,fo);


arguments (Input)
    xp {mustBeNumeric,mustBeReal,mustBeFinite,mustBeVector,mustBeUniform(xp)}
    yp {mustBeNumeric,mustBeReal,mustBeFinite,mustBeVector,mustBeUniform(yp),mustHaveSameSpacing(xp,yp)}
    ssh {mustBeNumeric,mustBeReal,mustBeCompatible(xp,yp,ssh)} 
    uo {mustBeNumeric,mustBeReal,mustBeFinite,mustBeVector}
    vo {mustBeNumeric,mustBeReal,mustBeFinite,mustBeVector}
    fo (1,1) double {mustBeReal,mustBeFinite}
end

arguments (Output)
    psip {mustBeNumeric,mustBeReal} 
    psi {mustBeNumeric,mustBeReal} 
    psif {mustBeNumeric,mustBeReal} 
end

%dx = xp(2)-xp(1);%this is the same between x and y
psif = zeros(length(yp),length(xp),length(uo));

[xg,yg] = meshgrid(xp,yp);

psi = (9.81/fo)*ssh/1000; %convert m^2/s to m km /s

for k=1:size(psi,3)
    %psiframe(:,:,k)=(vo(k)*(xg-xo(k))-uo(k)*(yg-yo(k)))*dx;
    psif(:,:,k)=(vo(k)*xg-uo(k)*yg);
end

psip = psi-psif;
end
