function createfigure_realEddy_mappedComparison(X1, YMatrix1, X2, Y1, X3, Y2, X4, Y3, X5, Y4, XMatrix1, YMatrix2, YMatrix3, Y5, Y6, Y7, YMatrix4, X6, YMatrix5, X7, XMatrix2, YMatrix6, YMatrix7, YMatrix8)
%CREATEFIGURE(X1, YMatrix1, X2, Y1, X3, Y2, X4, Y3, X5, Y4, XMatrix1, YMatrix2, YMatrix3, Y5, Y6, Y7, YMatrix4, X6, YMatrix5, X7, XMatrix2, YMatrix6, YMatrix7, YMatrix8)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  X2:  vector of plot x data
%  Y1:  vector of plot y data
%  X3:  vector of plot x data
%  Y2:  vector of plot y data
%  X4:  vector of plot x data
%  Y3:  vector of plot y data
%  X5:  vector of plot x data
%  Y4:  vector of plot y data
%  XMATRIX1:  matrix of plot x data
%  YMATRIX2:  matrix of plot y data
%  YMATRIX3:  matrix of plot y data
%  Y5:  vector of plot y data
%  Y6:  vector of plot y data
%  Y7:  vector of plot y data
%  YMATRIX4:  matrix of plot y data
%  X6:  vector of plot x data
%  YMATRIX5:  matrix of plot y data
%  X7:  vector of plot x data
%  XMATRIX2:  matrix of plot x data
%  YMATRIX6:  matrix of plot y data
%  YMATRIX7:  matrix of plot y data
%  YMATRIX8:  matrix of plot y data

%  Auto-generated by MATLAB on 18-May-2026 23:36:29

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[1.93770833333334 7.72875000000002 7.50000000000002 4.30000000000001],...
    'Units','centimeters');
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'DisplayName','$[1,10]$ day','Color',[0.65 0.65 0.65]);
set(plot1(2),'DisplayName','$[101,110]$ day','Color',[0.325 0.325 0.325]);
set(plot1(3),'DisplayName','$[251,260]$ day','Color',[0 0 0]);

% Create plot
plot(X2,Y1,'Parent',axes1,'LineWidth',1.5,'Color',[1 0.7 0.7]);

% Create plot
plot(X3,Y2,'Parent',axes1,'LineWidth',1.5,'Color',[0.85 0.35 0.35]);

% Create plot
plot(X4,Y3,'Parent',axes1,'LineWidth',1.5,'Color',[0.7 0 0]);

% Create plot
plot(X5,Y4,'Parent',axes1,'LineWidth',1,'LineStyle',':','Color',[0 0 0]);

% Create text
text('Parent',axes1,'FontWeight','bold','FontSize',18,'FontName','Times',...
    'String','(a)',...
    'Position',[-63.5042372881357 16.2531070681851 0]);

% Create text
text('Parent',axes1,'FontSize',11,'FontName','times','String','QG model',...
    'Position',[5.35169491525436 16.2060962864143 0],...
    'Color',[0.45 0.45 0.45]);

% Create multiple line objects using matrix input to plot
plot2 = plot(XMatrix1,YMatrix2,'Parent',axes1);
set(plot2(1),'DisplayName','Truth (Full field)','LineWidth',2,...
    'Color',[0 0 0]);
set(plot2(2),'DisplayName','Along-track','LineWidth',1.5,...
    'Color',[0.75 0.1 0.05]);

% Create ylabel
ylabel('SSH (cm)','FontName','times');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 250]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.644571638472745 15]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','times','FontSize',16,'XTickLabel','');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','FontSize',10);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[11.9431250000001 7.72875000000002 7.50000000000001 4.30000000000001],...
    'Units','centimeters');
hold(axes2,'on');

% Create multiple line objects using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',axes2,'LineWidth',2);
set(plot3(1),'Color',[0.65 0.65 0.65]);
set(plot3(2),'Color',[0.325 0.325 0.325]);
set(plot3(3),'Color',[0 0 0]);

% Create plot
plot(X2,Y5,'Parent',axes2,'LineWidth',1.5,'Color',[1 0.7 0.7]);

% Create plot
plot(X3,Y6,'Parent',axes2,'LineWidth',1.5,'Color',[0.85 0.35 0.35]);

% Create plot
plot(X4,Y7,'Parent',axes2,'LineWidth',1.5,'Color',[0.7 0 0]);

% Create plot
plot(X5,Y4,'Parent',axes2,'LineWidth',1,'LineStyle',':','Color',[0 0 0]);

% Create text
text('Parent',axes2,'FontWeight','bold','FontSize',18,'FontName','Times',...
    'String','(b)',...
    'Position',[-62.4225352112677 0.71564039408867 1.4210854715202e-14]);

% Create ylabel
ylabel('$\partial\eta/\partial r$ (cm\,km$^{-1}$)','FontName','times',...
    'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 250]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-2 0.5]);
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'FontName','times','FontSize',16,'XTickLabel','');
% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[1.96416666666668 1.75562500000001 7.50000000000003 4.30000000000002],...
    'Units','centimeters');
hold(axes3,'on');

% Create multiple line objects using matrix input to plot
plot4 = plot(X1,YMatrix4,'Parent',axes3,'LineWidth',2);
set(plot4(1),'DisplayName','$[1,200]$ day','Color',[0.65 0.65 0.65]);
set(plot4(2),'DisplayName','$[201,400]$ day','Color',[0.325 0.325 0.325]);
set(plot4(3),'DisplayName','$[801,1000]$ day','Color',[0 0 0]);

% Create multiple line objects using matrix input to plot
plot5 = plot(X6,YMatrix5,'Parent',axes3,'LineWidth',1.5);
set(plot5(1),'Color',[1 0.7 0.7]);
set(plot5(2),'Color',[0.85 0.35 0.35]);
set(plot5(3),'Color',[0.7 0 0]);

% Create plot
plot(X7,Y4,'Parent',axes3,'LineWidth',1,'LineStyle',':','Color',[0 0 0]);

% Create text
text('Parent',axes3,'FontWeight','bold','FontSize',18,'FontName','Times',...
    'String','(c)',...
    'Position',[-63.5042372881356 54.8059113300493 0]);

% Create text
text('Parent',axes3,'FontSize',11,'FontName','times',...
    'String','Agulhas Ring',...
    'Position',[4.46892655367235 53.1477832512316 0],...
    'Color',[0.45 0.45 0.45]);

% Create multiple line objects using matrix input to plot
plot6 = plot(XMatrix2,YMatrix6,'Parent',axes3);
set(plot6(1),'DisplayName','Truth (CMEMS)','LineWidth',2,'Color',[0 0 0]);
set(plot6(2),'DisplayName','Along-track','LineWidth',1.5,...
    'Color',[0.75 0.1 0.05]);

% Create ylabel
ylabel('SSH (cm)','FontName','times');

% Create xlabel
xlabel('Radial distance (km)','FontName','times');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 250]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[-10 50]);
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'FontName','times','FontSize',16);
% Create legend
legend2 = legend(axes3,'show');
set(legend2,'Interpreter','latex','FontSize',10);

% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[11.9695833333334 1.75562500000001 7.50000000000002 4.30000000000002],...
    'Units','centimeters');
hold(axes4,'on');

% Create multiple line objects using matrix input to plot
plot7 = plot(X1,YMatrix7,'Parent',axes4,'LineWidth',2);
set(plot7(1),'Color',[0.65 0.65 0.65]);
set(plot7(2),'Color',[0.325 0.325 0.325]);
set(plot7(3),'Color',[0 0 0]);

% Create multiple line objects using matrix input to plot
plot8 = plot(X6,YMatrix8,'Parent',axes4,'LineWidth',1.5);
set(plot8(1),'Color',[1 0.7 0.7]);
set(plot8(2),'Color',[0.85 0.35 0.35]);
set(plot8(3),'Color',[0.7 0 0]);

% Create plot
plot(X7,Y4,'Parent',axes4,'LineWidth',1,'LineStyle',':','Color',[0 0 0]);

% Create text
text('Parent',axes4,'FontWeight','bold','FontSize',18,'FontName','Times',...
    'String','(d)',...
    'Position',[-62.4225352112677 12.1564039408867 0]);

% Create ylabel
ylabel('$\partial\eta/\partial r$ (cm\,km$^{-1}$)','FontName','times',...
    'Interpreter','latex');

% Create xlabel
xlabel('Radial distance (km)','FontName','times');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0 250]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[-15 10]);
hold(axes4,'off');
% Set the remaining axes properties
set(axes4,'FontName','times','FontSize',16);
